title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

markdown: kramdown
baseurl: /tutorialesDAW

collections:
  asignaturas:
    output: true
    output_ext: .html
    permalink: ./asignaturas/:name.html

baseurl: tutorialesDAW


