title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

collections:
  asignaturas:
    output: true
    output_ext: .html
    permalink: /asignaturas/:path/
  
